spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/ExerciseTeamD
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.type-aliases-package=com.example.demo.mybatis.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.example.fullness.stationary.mybatis.entity
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

